---
title: "Reading around the thesis"
author: "Fiona Bradley"
categories: [writing]
editor: visual
date: '2023-06-17'
---

I'm often asked, such as in a recent webinar on research for ALIA, "how is your thesis going, anyway?". Depending on the day I'll either respond, "still going", or launch into a long-winded overview of my latest observations. Fitting a part-time PhD around a day job and other professional commitments is not something to take on lightly.

Con asks, [how do you find books to read?](https://flexnib.com/2023/06/16/books-to-read/) My research spans some very fast moving topics and there is a lot to keep up with. At the same time, I have been warned to not read too much. It's a balancing act especially when getting up to speed with a new area quickly.

Many reading sources come from traditional research advice: find a key scholar or work in a field, read them, and citation chain to identify other relevant materials. [Foreign Affairs](https://www.foreignaffairs.com/), [The Economist](https://www.economist.com/culture/2022/12/06/these-are-the-economists-best-books-of-2022), [LA Review of Books](https://lareviewofbooks.org/) and [Arts & Letters Daily](https://www.aldaily.com/) are mainstays for book reviews. ISA's annual [human rights book award](https://www.isanet.org/Programs/Awards/HR-Best-Book) is also worth checking.

Social media, especially Twitter, has also helped me find many relevant books. After Musk's acquisition of Twitter, I set up a profile on Mastodon and combed through every account I followed to subscribe to newsletters and feeds in case their profile disappeared. Yet most scholars I follow have not migrated away from Twitter. The resulting information overload in following and digesting so many sources to find relevant information is very much felt.

At the same time, while there is danger in reading too much, I am a great fan of 'reading around' to have a better sense of history, context, and culture especially when working on somewhat technical, sometimes very dry research topics. This also provides an opportunity to introduce a broader range of sources into the mix, or simply ideas that run parallel to a research question. Some recent books that I've enjoyed in this vein:

Jing Tsu, *Kingdom of characters: The language revolution that made China modern*\
Megan Walsh, *The Subplot: What China is reading and why it matters*\
Frank Dikötter, *China after Mao\
*Jenny Odell, *How to do Nothing*

In the era of generative AI where many of the conversations about the use of text tools to effectively game learning is leading to a very narrow approach where students only want to be exposed to ideas that have the greatest utility (ie, 'is this on the test?'), I find it essential to make time for reading broadly and for fun. Even if the result is that the thesis is "still going". It will all get done, one day.
