project:
  type: website

website:
  title: "Fiona Bradley"
  site-url: fionabradley.com
  description: "Fiona Bradley"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual



